// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function GetCSSVariables() {
	// BEGIN USER CODE
	const page =document.querySelector("div[data-testid=shadow-root-host]").shadowRoot.querySelector(".mx-page");

	if (page === undefined) {
		return ".mx-page not found";
	}

	const rootCSSVariable = window.getComputedStyle(page).getPropertyValue("--root-variable");
	const bodyCSSVariable = window.getComputedStyle(page).getPropertyValue("--body-variable");

	return `--root-variable: ${rootCSSVariable}, --body-variable: ${bodyCSSVariable}`;
	// END USER CODE
}
