// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("49052541-d46d-4ae5-b449-bfc42a482953"),
	English("bccd395e-db52-4b53-9dc2-33f967bf3219"),
	French("797a046c-51d7-4eb5-aa86-983f37ab53d2"),
	German("91925017-96f7-4c71-a6ef-1ece653b4b9d"),
	Hindi("2658e043-fb2f-4c8b-9ac5-50ef0eb31459"),
	Portuguese("ccce3176-837b-4fc9-ab49-0956fa1fd00f"),
	Spanish("957527bc-6bb9-4805-a979-0866e31df161"),
	Turkish("9e1df063-b0b4-43e0-ad5b-6795f2412c12");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
