// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("a5ee2bef-28e9-462e-9583-96ca76d9de5a"),
	startsWith("73fdf0ef-55e8-472f-9bdc-a238bc2d76c3"),
	endsWith("fdb97f5b-8077-4055-b12e-9f8ea30a5292"),
	between("1d9a91bc-94e4-4279-81b3-ae8723bfe5cc"),
	greater("8d6688ac-f07d-4dee-b9ff-f2b00f02ed91"),
	greaterEqual("00798354-2a3a-4036-a0a2-4e9f7f885817"),
	equal("f6ac66a0-123e-4efa-9f66-ac8ee4dc82ac"),
	notEqual("73a4fdee-1511-47e5-99a0-8843684443dd"),
	smaller("f9b28d89-97a5-4188-bb72-c4341cc19741"),
	smallerEqual("b562d2e0-adb9-4680-b28e-b0b2d0bc54f1"),
	empty("551a26aa-4f41-4a9c-b9ad-0978c3323fe1"),
	notEmpty("bc72a8e2-175c-46b8-bca2-a86e848fff7b");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
