// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("029ce2cd-d3ca-42dc-8b46-5a7f41cefe26"),
	Geocodio("bd672c63-a581-49f8-91f7-f4057b1d6e10"),
	LocationIQ("d32210bc-b4f5-4650-b775-adfcfd394b46"),
	MapQuest("9b49dde8-a6fd-4b78-96bd-a985a4c1ceb7");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
