// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("fc2e1833-857c-4add-9de0-36f5491cc13b"),
	low("4c097211-431b-40fc-8d71-47aea12314ae"),
	medium("ee56bd7b-4b78-49b9-af96-ff331dc4db9b"),
	high("ea497801-b4cd-4043-b68a-71765517ca78"),
	custom("d582f8cf-e4ee-48f0-83b3-d8773e59e59d");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
